//sensor setup-col_reflect
#pragma config(Sensor, S3, reflectedValue, sensorEV3_Color,modeEV3Color_Reflected)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
#define THRESHOLD 50
task main()
{
	motor[motorB] = 30;
	motor[motorC] = 30;

	while (SensorValue(reflectedValue) < THRESHOLD) {
		
		playSound(soundBlip);
		wait1Msec(1000);
	}

	motor[motorB] = 30;
	motor[motorC] = 30;

	while (SensorValue(reflectedValue) < THRESHOLD) {

		playSound(soundBlip);
		wait1Msec(1000);
		playSound(soundBlip);
		wait1Msec(1000);
	}

	motor[motorB] = 30;
	motor[motorC] = 30;

	while (SensorValue(reflectedValue) < THRESHOLD) {

		playSound(soundBlip);
		wait1Msec(1000);
		playSound(soundBlip);
		wait1Msec(1000);
		playSound(soundBlip);
		wait1Msec(1000);
	}

	motor[motorB] = 30;
	motor[motorC] = 30;

	while (SensorValue(reflectedValue) < THRESHOLD) {

		playSound(soundBlip);
		wait1Msec(1000);
		playSound(soundBlip);
		wait1Msec(1000);
		playSound(soundBlip);
		wait1Msec(1000);
		motor[motorB] = 0;
		motor[motorC] = 0;
	}

}
